### ISSUE TITLE
Error: login via port forwarding

### ISSUE THREAD

**Issue by djb79** [rvolz/BicBucStriim#112]
Hey,

when I try to login to BicBucStriim 1.2.4 from outside my network through DynDNS and port forwarding, it is difficult to login: I do enter name and password and press "login", but then nothing happens. Sometimes it shows "Error loading page". So it seems, as if I can not log in. But when i choose a categorie from above (books, authors), everything works fine.

So I assume, that logging in does work properly, but it does not automatically load the right page after logging in. But why?

**Comment by buffos** [comment]
Its an old post, but i just stumbled on that problem

For example let's say you have a domain in dyndns... mycomputer.net
and you port forward port 100000 to the synology computer at port 80

when you do mycomputer.net:100000/bbs/opds/
you are asked for user name and password and once logged in you see the xml feed.

and there you see the problem. All links there are 

mycomputer.net/bbs/opds/XXXXX    . The port has been stripped, so all links are broken

Locally it works because the default port is 80. If that is changed it will not work either

**Comment by rvolz** [comment]
Which version are you using? At least in the current Github version this shouldn't be a problem anymore. 

It uses relative URLs by default, which should keep the port. If this doesn't work in your case, you could try to send forwarding information, see https://github.com/rvolz/BicBucStriim/wiki/Forwarding

**Comment by buffos** [comment]
I am using the one "compiled as a package" by Synocommunity for Synology, so i guess i will first have to mail them

Thanks for your reply!

**Comment by rvolz** [comment]
Then you'll have to wait for a little while. They track the release versions, and the current Github version will probably be released during the next weekend.
