### ISSUE TITLE
Login page empty and not working after install

### ISSUE THREAD

**Issue by gcraenen** [rvolz/BicBucStriim#192]
Error:
"Not Found

The requested URL /login/ was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 192.168.88.164 Port 80"

Install went fine and installcheck gives a "green" board.

Removing the inlog option in the admin menu shows the main page, but after that every option I "click" gives a "error loading page" error.

When I try to add a new user it gives "Error while applying changes" as the error.

Something wrong with permission settings?? I did a chown -R www-data:www-data (Ubuntu server), but that didn't change anything.

**Comment by rvolz** [comment]
What version are you using?

You could switch on the debug mode to find out more. Open `index.php` and change the following part at the top of the file:

```php
# Init app and routes
$app = new \Slim\Slim(array(
    'view' => new \Slim\Views\Twig(),
    'mode' => 'production',
    #'mode' => 'debug',
    #'mode' => 'development',
));
```

to

```php
    #'mode' => 'production',
    'mode' => 'debug',
```

After the change log files will appear in the `data` directory, and you might see error messages in the browser. That should help to identify the problem.

**Comment by gcraenen** [comment]
Hi,

Thanks for responding.

I changed this setting, it gave me the following in the log file:

INFO - 2015-11-26T14:08:49+01:00 - BicBucStriim 1.3.6: Running in debug mode.
DEBUG - 2015-11-26T14:08:49+01:00 - easy mode: login not required
DEBUG - 2015-11-26T14:08:49+01:00 - own_config_middleware: config loaded
DEBUG - 2015-11-26T14:08:49+01:00 - login resource: /

Unfortunately nothing more. Everything I clicked on gave me the message “Error loading page"

Regards,


G.H.M. (Guido) Craenen

**Comment by rvolz** [comment]
I checked the error message you reported in the first post, and that implies that something is wrong with either the database or the permissions. However, somehow you were able to save some settings in the admin page. So it's probably not the permissions, because then you wouldn't have been able to change settings via the admin page.

So you could

1. replace the file `data/ data.db` with a fresh copy from the archive or from https://github.com/rvolz/BicBucStriim/raw/master/data/data.db
1. use some JavaScript console in the browser, like Firebug for Firefox, to look at the error messages in the browser

My test system uses Ubuntu and I can't reproduce the error there.

**Comment by gcraenen** [comment]
I’ve exchanged the data.db file but that didn’t solve it. Thanks for helping out so far, but I’m switching over to the COPS program, that’s easier for me to install and get working.

Regards,


G.H.M. (Guido) Craenen
