### ISSUE TITLE
After search for Author and finding 4 books, only 2 books are shown

### ISSUE THREAD

**Issue by Maurice69** [rvolz/BicBucStriim#194]
When I search for an author I find 4 books. Then I click it and only see 2 of the 4 books, where are the other books? ;-)
![bbs1](https://cloud.githubusercontent.com/assets/7605620/11530435/ec0c23ba-98f4-11e5-8a58-8f4364fd98b7.jpg)
![bbs2](https://cloud.githubusercontent.com/assets/7605620/11530434/ec06710e-98f4-11e5-88b5-49a248521ee2.jpg)

Regards,

Maurice

**Comment by rvolz** [comment]
They were filtered out, I guess. This behaviour happens when the user account has set filters for language and/or tags. 

In the interest of speed the first step of the search doesn't use filters, so you get the total count of books. But if you try to access books, you' ll only see the ones that you are allowed to see.

**Comment by Maurice69** [comment]
I installed it again, deleted the cookies and left the settings of the users for what they are and now the books are shown. I think this needs a little attention because changing the settings in the admin didn't help. Can I use the 1.3.5 version instead of the synology 1.2.5 release?

**Comment by rvolz** [comment]
Thx for the heads up. I'll check that again. 1.3.5 seems to be stable. If there are no complaints during the next days, I'll publish this version on the website. Synocommunity follows the website releases,

**Comment by Maurice69** [comment]
Thnx for your help Rainer!
