### ISSUE TITLE
Previous books not showing anymore

### ISSUE THREAD

**Issue by ThomasDaheim** [rvolz/BicBucStriim#217]
Hi,

first of all thanks for a great tool - using it for quite a while now to access my books from various devices :-)

Today I ran into an issue similar to #130:

- all my logins didn't work anymore (admin / admin worked, so I re-created all others)

- all books except 3 are gone - only 3 shown under books BUT all counts shown under tags & authors

Any idea what could have caused this and how I could get back to access my books?

Also, the download front-end now looks different when accessed by aldiko reader from android. But that might have been a version update? I'm running 1.3.6

installcheck.php doesn't show any isssues...

Thanks in advance for any hints,
Thomas

**Comment by rvolz** [comment]
_Hidden_ books are usually the result of a filter in the user account. They can be removed in the the user section.

Did you update manually, or update automatically via Synology? Normally BicBucStriim doesn't delete user accounts. However, it creates an empty data.db with only an admin account if it can't find an existing data.db.

**Comment by ThomasDaheim** [comment]
The update was done automatically via Synology.

I just checked: I don't have any tags selected for any user. BUT under data/titles I only have three pngs for the three books shown...

Is there any way to force bbs to re-scan the books folder?

**Comment by rvolz** [comment]
The icons will be automatically re-created when the titles will be displayed, no re-scan necessary. 
Since the problems seem to arise from the update you have the following options:

1. You could try to delete the file data/data.db. Then BicBucStriim will try to create a new one, hopefully without problems.
2. Re-install the Synology module

Both options would mean that you would have to enter the user data again, sorry.

**Comment by ThomasDaheim** [comment]
Deleting data/data.db worked - luckily I only have one user :-) Thanks!
