### ISSUE TITLE
Download books to Google Chrome on iOS

### ISSUE THREAD

**Issue by Hiraka1** [rvolz/BicBucStriim#245]
There is an issue/bug in downloading books to an iOS device. (iPad, iPhone) and using the browser Google Chrome.  When I choose one book no matter epub or mobi or pdf, it only shows "Cannot determine file size" and it downloads a 4KB document.
Is there any solution for it? 
Safari just works fine. Google Chrome on Android phones/tablets just works fine too.

**Comment by rvolz** [comment]
Chrome on iOS: 

* first downloads the book successfully, but apparently just to get the file size
* it doesn't understand the file size (?) although that is sent correctly
* then tries to download the book again (when you click the "download" link), this time unfortunately by forgetting to send the authorization
* because there is no authorization bicbucstriim refuses to send the book (the 4K you get is just the login page)

The "Cannot determine file size" problem is known, but apparently there is no solution. The only workaround for these problems is/was to disable authorization. Then suddenly Chrome knows about the file size and can download properly. Sorry.
