### ISSUE TITLE
Can't download Epubs

### ISSUE THREAD

**Issue by csgnyc** [rvolz/BicBucStriim#246]
I can access BicBucStriim OK, can download PDFs, but cannot download Epubs.  Chrome gives me "The [synology IP] page isn’t working

[synology IP] is currently unable to handle this request.
HTTP ERROR 500"

Ran installcheck and everything looked OK.

1) I recently upgraded to Synology DSM 6.1, so this may relate to the problem.  
2) Web Station now tells me that the HTTP Backend Server is "Apache HTTP Server 2.2" and PHP is "PHP 5.6".  When I first noticed the problem, it seemed that Apache 2.2 had stopped running, but by stopping Apache 4.4, I was able to get Apache 2.2 to restart.

**Comment by csgnyc** [comment]
By turning off the option to update metadata when downloading, I was able to evade this issue.  Don't know if that means there's a bug someplace.

**Comment by rvolz** [comment]
I haven't had other reports for that part of the code, and for me downloading still works with or without metadata update. If could be still a rights issue, because the metadata update includes copying the book file to some temporary location.

If you want to find out more about the problem, switch on [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) and metadata update. The log files should then contain more details about the source of the error.

**Comment by Deanna4711** [comment]
I can confirm the issue. Same problem here. With "Update Metadata on" there is no download possible. If I turn off, no problem. 
Thanks @csgnyc  for temporarily solution.
@rvolz I hope you`re able to repair the issue, BicBucStriim is a great projekt! I`m glad to find it.

**Comment by rvolz** [comment]
Thanks @Deanna4711  for the confirmation, but without an error log (see above) there is not much I can do.

**Comment by Deanna4711** [comment]
@rvolz  
Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 2
Message: tempnam(): open_basedir restriction in effect. File(/var/services/tmp) is not within the allowed path(s): (/volume1/web/bbs:/volume1/web/bbs:/volume1/Bibliothek_online)
File: /volume1/web/bbs/lib/BicBucStriim/metadata_epub.php
Line: 37
Trace

#0 [internal function]: Slim\Slim::handleErrors(2, 'tempnam(): open...', '/volume1/web/bb...', 37, Array)
#1 /volume1/web/bbs/lib/BicBucStriim/metadata_epub.php(37): tempnam('/var/services/t...', 'bbs_epub_')
#2 /volume1/web/bbs/index.php(1311): MetadataEpub->__construct('/volume1/Biblio...')
#3 [internal function]: book('14244', 'Die Entfuhrung ...')
#4 /volume1/web/bbs/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('book', Array)
#5 /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()
#6 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /volume1/web/bbs/lib/BicBucStriim/calibre_config_middleware.php(50): Slim\Middleware\MethodOverride->call()
#9 /volume1/web/bbs/lib/BicBucStriim/login_middleware.php(36): CalibreConfigMiddleware->call()
#10 /volume1/web/bbs/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware->call()
#11 /volume1/web/bbs/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#12 /volume1/web/bbs/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#13 /volume1/web/bbs/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#14 /volume1/web/bbs/index.php(206): Slim\Slim->run()
#15 {main}

[2017-11-22.log](https://github.com/rvolz/BicBucStriim/files/1496816/2017-11-22.log)

**Comment by rvolz** [comment]
Ok, it's a rights problem. To solve it just add the TEMP directory mentioned in the error -- in this case `/var/services/tmp` --  to your _open_basedir_  setting -- that is the same where added your Calibre library in WebStation.

Caveat: the name of that TEMP directory depends on the OS used. In case of Synology it is `/var/services/tmp`, it might be different for others.
