### ISSUE TITLE
problems with ginx und php-gd2

### ISSUE THREAD

**Issue by noadminonly** [rvolz/BicBucStriim#249]
Hello 

Today i install bibucstrim on my raspberry. On the installation check site there ist shown, that i have no  GD Version installed. 

But if I check my php installation  I found 

GD Support	enabled
GD headers Version	2.1.1-dev
FreeType Support	enabled
FreeType Linkage	with freetype
FreeType Version	2.5.2
GIF Read Support	enabled
GIF Create Support	enabled
JPEG Support	enabled
libJPEG Version	6b
PNG Support	enabled
libPNG Version	1.2.50
WBMP Support	enabled
XPM Support	enabled
libXpm Version	30411
XBM Support	enabled
WebP Support	enabled

any Ideas was wrong on my system? 

noadminonly

**Comment by rvolz** [comment]
Probably nothing. The installcheck script uses phpinfo() to get the information, and that changed,  see #204. The fix for that was already [commited](https://github.com/rvolz/BicBucStriim/commit/aa140e6c25f31872255ffa48d561d9f6700ab79a), but is not yet released.

If the thumbnails for the books are generated, then everything is ok with your system.

**Comment by rvolz** [comment]
Was released with 1.4.1
