### ISSUE TITLE
BBS on Synology Error when downloading

### ISSUE THREAD

**Issue by yabdali** [rvolz/BicBucStriim#266]
Hi,

I installed BBS using Synocommunity package in DS 6.1.  When I use to the browser to navigate through different titles I got, I get the error below.  The error shows every time I click to download any of the books.  Example for PDF file download link that generates the error is below.  Appreciate your help?

Notes:
Configuration page reports everything working OK. My library resides in /volume1/mycloud/Books/ and is included in base dir for php under webstation settings. 

Error Message:
http://xxxxx/bbs/titles/11/file/The%20Challenger%20Sale_%20Taking%20Con%20-%20Matthew%20Dixon.pdf

Warning: Declaration of BicBucStriim\SegmentFactory::newInstance(BicBucStriim\Session $session, $name) should be compatible with Aura\Session\SegmentFactory::newInstance(Aura\Session\Session $session, $name) in /volume1/web/bbs/lib/BicBucStriim/segment_factory.php on line 16

**Comment by rvolz** [comment]
That problem appeared in newer PHP versions, see #208. It was fixed in version 1.4, which is probably not yet available as a SynoCommunity package. 

In the meantime you could 

1. Contact the SynoCommunity maintainer and ask for a newer version
1. install version 1.4 manually
1. change the PHP error reporting as documented here https://stackoverflow.com/questions/9983286/disabling-strict-standards-in-php-5-4

Hope this helps
