### ISSUE TITLE
Email function not working

### ISSUE THREAD

**Issue by simistef** [rvolz/BicBucStriim#270]
Hi,

I cannot send emails to my kindle device neither wit PHP Mail nor Send Maiol (i do not use SMTP).

In the interface i get the error: Somethin went wrong. Please check email address.

Both email are OK (from and to).

These are the logs from debug mode:

INFO - 2018-01-24T08:15:27+02:00 - BicBucStriim 1.3.6: Running in debug mode.
INFO - 2018-01-24T08:15:27+02:00 - multi user mode: login required
DEBUG - 2018-01-24T08:15:27+02:00 - own_config_middleware: config loaded
DEBUG - 2018-01-24T08:15:27+02:00 - login resource: /titles/687/kindle/Everything%2C%20Everything%20-%20Nicola%20Yoon.mobi
DEBUG - 2018-01-24T08:15:27+02:00 - after resume: VALID
DEBUG - 2018-01-24T08:15:30+02:00 - kindle: requested file /volume1/ebooks/calibre/Nicola Yoon/Everything, Everything (687)/Everything, Everything - Nicola Yoon.mobi
WARN - 2018-01-24T08:15:33+02:00 - kindle: book delivery to s*******.u*******e@kindle.com failed, dump:

**Comment by rvolz** [comment]
Are there further details about the problem?  They would appear after the last line you sent, "dump:"

SMTP is recommended because PHP Mail and Sendmail (which PHP Mail uses somehow) depend on your system's configuration. 

Over the years I had mixed success with the latter two on the Synology NAS. Currently the PHP Mail works on DSM 6.2, Sendmail accepts the mail but doesn't deliver it. Apparently you can get Sendmail to work by installing the MailServer package and configure it as an SMTP relay.

I have the MailServer package installed but without any SMTP functionality. Maybe that helps somehow. Unfortunately I have no time to debug this.

**Comment by simistef** [comment]
No further details.

I did install version 1.4.1 and remoced the login did a NAS restart and seems to work now. However there are some problems with the books being sent. I receive error via email that the document could not be delivered.

However if i download manually the .mobi file and send it via email client it is delivered succesfully. 

Here is the log:

INFO - 2018-01-25T09:38:05+02:00 - BicBucStriim 1.4.1: Running in debug mode.
DEBUG - 2018-01-25T09:38:05+02:00 - easy mode: login not required
DEBUG - 2018-01-25T09:38:05+02:00 - own_config_middleware: config loaded
DEBUG - 2018-01-25T09:38:05+02:00 - login resource: /titles/1286/kindle/0062413406%20%28N%29%20-%20Duncan%20Clark.azw3
DEBUG - 2018-01-25T09:38:06+02:00 - kindle: requested file /volume1/ebooks/calibre/Duncan Clark/0062413406 (N) (1286)/0062413406 (N) - Duncan Clark.azw3
DEBUG - 2018-01-25T09:38:17+02:00 - kindle: book delivered to s*****n.u*******e@kindle.com, result 1

**Comment by rvolz** [comment]
The email works. It's the same for all three sending methods.

The problem rather seems to be the file format: you mentioned sending a MOBI file successfully, but the app sent the AZW3 version! The current algorithm prefers AZW3 to MOBI, see #214.

For the time being you could use the workaround mentioned there.
