### ISSUE TITLE
Searching again

### ISSUE THREAD

**Issue by Roemke** [rvolz/BicBucStriim#283]
Hello, 
first thanks - I found this fine project just a day ago and tried it on a raspberry pi using lighttpd and php7.0. It is the actual stretch version of raspbian.
I can exactly reproduce the problems mentioned in #event-1526810442
If I try to search I get the message Error Loading Page
I have enabled debug mode in index.php and I look into /var/log/lighttpd/error.log and in data/<date>.log
I can't find any hints according my search,  I'm a little astonished by the debug output. 
The last lines (recorded while searching) are as follows:
INFO - 2018-03-22T23:04:54+01:00 - BicBucStriim 1.4.1: Running in debug mode.
DEBUG - 2018-03-22T23:04:54+01:00 - easy mode: login not required
DEBUG - 2018-03-22T23:04:54+01:00 - own_config_middleware: config loaded
DEBUG - 2018-03-22T23:04:54+01:00 - login resource: /titles/591/thumbnail
DEBUG - 2018-03-22T23:04:54+01:00 - thumbnail: 591
INFO - 2018-03-22T23:04:54+01:00 - BicBucStriim 1.4.1: Running in debug mode.
INFO - 2018-03-22T23:04:54+01:00 - BicBucStriim 1.4.1: Running in debug mode.
INFO - 2018-03-22T23:04:54+01:00 - BicBucStriim 1.4.1: Running in debug mode.
DEBUG - 2018-03-22T23:04:54+01:00 - easy mode: login not required

The lighttpd error log says nearly nothing
2018-03-22 22:17:20: (log.c.217) server started 
2018-03-22 22:34:08: (server.c.1828) server stopped by UID = 0 PID = 1 
2018-03-22 22:34:09: (log.c.217) server started 

The mentioned issue is closed so I "reopen it" to ask if there are new ideas or if the problem is solved. 
Thanks 
Karsten

**Comment by rvolz** [comment]
What was the issue you are referring to? #event-1526810442 doesn't tell me anything

**Comment by Roemke** [comment]
Sorry I saw the reference sign in the editor - so I've hoped it will refer to the issue - I have to read the manual of githubs editor. 
The issue I refer is [https://github.com/rvolz/BicBucStriim/issues/250](https://github.com/rvolz/BicBucStriim/issues/250) 
Thanks for answering.
Karsten

**Comment by rvolz** [comment]
Ok, thanks. The debug output was used to solve problems in the early phase of the project, I guess it looks strange now. 

If there is no error in the log, you could look at the browser console, if there is some error message. But I guess the problem is related to the URL rewriting, as mentioned in #250. When I last tried Lighttpd on a Raspi the [documented solution](https://github.com/rvolz/BicBucStriim/wiki/WebServers#lighttpd-on-raspberry-pi) worked for me. Apparently that changed in the meantime.

The point is to make sure that index.php gets the right arguments (e.g. for URL `http://server/bbs/search/?search=test` that would be `/search/?search=test`) and that certain paths (style|img|js|installcheck.php) are not handled by index.php. If the thumbnails only appear the first time and not afterwards, that indicates the URL rewriting has problems. And that will cause other problems with search etc.

Unfortunately I don't use Lighttpd, so I can't help you there. Maybe someone else?

**Comment by Roemke** [comment]
I've installed apache2 and it works out of the box, so my further questions are just because I like to understand. 
As far as I understand the rewriting an url like http://server/bbs/search/?search=test should be translated to http://server/bbs/index.php?/search/search=test - is this right? ([QSA,L]) in directive
I think I'm wrong, because if I directly call http://server/bbs/index.php?/search/search=test I get the homepage without css and thumbs. (using apache2).
I've tried to analyse the rewriting apache2 do by enabling logging by the directive 
LogLevel alert rewrite:trace6
but I have no success in interpreting the massive output :-(
Before I try again with lighttd rewrite rules I would like to have a confirmation that this is the correct rewrite apache2 should perform. 
Thanks 
 Karsten

**Comment by rvolz** [comment]
The .htaccess has the line `RewriteRule ^(.*)$ index.php [QSA,L]` which means: always call index.php and add the query string. So the URL `http://server/bbs/search/?search=test` is probably rewritten as `http://server/bbs/index.php?search=test`. Internally PHP looks at the global variables _SERVER["REQUEST_URI"], which contains `/bbs/search/?search=test`, and _SERVER["QUERY_STRING"], which contains `search=test`. 

From this information the PHP framework deduces what to do. So it is no real _rewriting_, but that is the pattern many PHP applications use. You can see that spelled out in the rewriting rules for [nginx](https://github.com/rvolz/BicBucStriim/wiki/WebServers#ngnix-on-raspberry-pi). 

Maybe you should try to find recent Lighttpd rules for common PHP applications, like WordPress, and try them out.
