### ISSUE TITLE
Newest books on start page

### ISSUE THREAD

**Issue by joticakr** [rvolz/BicBucStriim#300]
BBS didn't refresh the newest book list on the start page. It still shows the books I had with the first run of BBS. Is there a chance to refresh manually?

**Comment by joticakr** [comment]
Sure, I understand that the added date is provided by calibre. If I add new books to calibre the recent list at the BBS start page won't change.

**Comment by rvolz** [comment]
Yes, the list on that page works by using the Calibre timestamp, which is the date of creation. So new, _added_, titles should always appear there! Changes (eg new versions of the book files) are usually not reflected there. Since it is the purpose of the start page to show the added books, there is no manual override.

You could check that by using the _titles_ view with _time_ ordering. In the configuration you can select what time-property of Calibre is used for ordering. If you selected _date added_ there then titles listed should be identical for both pages.

If the new books you are looking for don't appear in both pages, then usually the Calibra database is outdated.

**Comment by joticakr** [comment]
OK, I found my mistake in calibre. Anyway, thank you very much for your help.
