### ISSUE TITLE
Reverse "Optional, don't show books with this tag"

### ISSUE THREAD

**Issue by Alacard** [rvolz/BicBucStriim#321]
is there a way to reverse "Optional, don't show books with this tag" option to where it will only show a section tag and not hide it?

Example. create a new user called bob and set that option to "KidFriendly", so when that user login via web or opds they will only get shown books that has a "KidFriendly" tag and nothing else.

**Comment by rvolz** [comment]
No, unfortunately there is not. The idea there was to be able to hide only certain tags/categories. Only the language filter is positive.

One workaround would be to have a separate BicBucStriim installation for the "KidFriendly" books.

**Comment by bkqc** [comment]
I would also find it very useful if we could assign specific tags to specific users as a mean of having some level of "user security". Could it be possible to add this as a feature request?

**Comment by bkqc** [comment]
> No, unfortunately there is not. The idea there was to be able to hide only certain tags/categories. Only the language filter is positive.
> 
> One workaround would be to have a separate BicBucStriim installation for the "KidFriendly" books.

When you say a separate user for KidFriendly library, since there is actually no way of positively filtering on tags, how would you recommend to do it? With a completely different Calibre database?

**Comment by bkqc** [comment]
@Alacard Though this is not a definitive solution since the UI won't follow and that it is a global setting, if your need is simply to have some user use a _KidFriendly_ version of your library, here are some simple changes you could do to your PHP files to reverse the tag filter behavior. It uses the same UI as the negative filter.

If a definitive solution was to be developed around this modification, I think it would be a great idea to have the behavior modifiable per user instead of globally.

Disclaimer: You are responsible for the changes you make and I could not be hold responsible for any harm done by these modifications.

The behavior can be reversed by modifying this new global setting `$globalSettings[POSITIVE_TAG_FILTER] = true;`
Files are based on v1.5.3 and specific changes can be found by searching for `//BKExt` to apply them manually to possibly any version.
[BicBucStriimReverseTagFilter.zip](https://github.com/rvolz/BicBucStriim/files/8508460/BicBucStriimReverseTagFilter.zip)
