### ISSUE TITLE
Series are empty, Cover current cover only in detail

### ISSUE THREAD

**Issue by K1ngLear** [rvolz/BicBucStriim#332]
Hi,

I run you fabulous software on my Synology and the most things are fine. Unfortunately I encountered two issues. Meanwhile the numbers by a series or an author give back the correct count of books in it, the detail page of a series or an author are sometimes empty. 
The second one is the missing of the actual cover in the overview. 

Thx

**Comment by rvolz** [comment]
1) That can happen if a **filter** was defined for a user. Filtering was only meant for parental control, limiting access to certain books. Due to that and to performance limitations the filtering doesn't happen everywhere. While direct access to a detail page or downloads is prohibited, the titles are included in _counters_. 

2) Thumbnails of covers in listings are generated on the fly and stored in the `data/titles` directory of your installation. You could check if the files exist there. If not, you could enable [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode), to look for errors.
