### ISSUE TITLE
No access from outside the WLAN to bbs

### ISSUE THREAD

**Issue by huber72** [rvolz/BicBucStriim#338]
Moin,

installed bbs on Synology, all rights are given, access within WLAN is ok, no problem on differnet tablets, smartphones, PC and notebook.

But: No access from outside (while travelling), page /ip cannot be found

Where is my fault?

Peter

**Comment by davkastheranger19** [comment]
You probably have to open ports 80 and 443 in your modem/router/firewall and forward them to the LAN IP of the Webserver.
Find your WAN IP and then try to telnet into the WAN IP on port 80 and 443.

**Comment by huber72** [comment]
Thanks for reply, but I have no understanding in things like that :-(

**Comment by huber72** [comment]
Foolish Question in addition: I am able to connect to Synology station from outside via DSM "quickconnect" using

http://quickconnect.to/xyz123

May I enlarge this adress in order to enter bbs/login?

**Comment by davkastheranger19** [comment]
> Foolish Question in addition: I am able to connect to Synology station from outside via DSM "quickconnect" using
> 
> http://quickconnect.to/xyz123
> 
> May I enlarge this adress in order to enter bbs/login?

Quickconnect works by your NAS opening an outbound port from your LAN and communicates to synology. When you connect externally to the quickconnect address, your request go to synology and checks what port your NAS opened on the outbound connection and then you take the connection over from synology coming in on the port that your NAS opened. That is why quickconnect works without having to open any ports on your firewall/modem/router. Those devices usually allow outbound connections without issue but block all inbound traffic that was not originally started from an outbound connection.
 Because of this, you cann't piggy back on quickconnect.to. You will have to open your modem/router/firewall to connect to your webserver.

**Comment by davkastheranger19** [comment]
> Thanks for reply, but I have no understanding in things like that :-(

Then it's probably in production mode. I've started looking into this as the timer is not working for the 1-day cookie. I'll let you know if I was able to figure out why it's terminating the connection prior to the cookie expiration.
