### ISSUE TITLE
bbs displays author as ABC| DEF

### ISSUE THREAD

**Issue by huber72** [rvolz/BicBucStriim#339]
Moin,

All my authors within calibre are tagged by using "surname, first name"  but are displayed in bbs as "surname| first name"

I have no idea what the stroke stands for but like to replace it by a comma - where have I to change this?

Thanks, Peter

**Comment by rvolz** [comment]
What do you mean with "tagged"? There are real "tags" with the author names?   Or the author names elsewhere? Could you please give an example? 

In any case, BBS doesn't change author names, except for escaping in some situations. But to check that I would need a more concrete example.

**Comment by huber72** [comment]
Moin,

I guess we both know what tags are.... No necessity to explain and:

I didn't mention that bbs changes author's names but displays it in a strange way:

Agatha Christie's "16 Uhr 50 ab Paddington" is authorwise described/tagged with "Christie, Agatha"
Looks well within the table of authors, but if you run the author to look for the respective books and /or view a book details the stroke appears between "Christie" and "Agatha"

![Unbenannt](https://user-images.githubusercontent.com/60315804/88564131-202dbf80-d033-11ea-90eb-8f655c505c9f.JPG)
![Unbenannt1](https://user-images.githubusercontent.com/60315804/88564133-215eec80-d033-11ea-906d-e4a49f5e944c.JPG)
![Unbenannt2](https://user-images.githubusercontent.com/60315804/88564134-21f78300-d033-11ea-920f-a05abf5002f6.JPG)

**Comment by rvolz** [comment]
Thx for the info. The bad news is: everything works as designed ;-) 

Calibre has two name fields for authors:

1. the regular name, eg "Agatha Christie"
2. the sort field, eg "Christie, Agatha"

<img width="646" alt="grafik" src="https://user-images.githubusercontent.com/1092531/88671338-7871c980-d0e6-11ea-935d-0bb11b779817.png">

If you follow this standard, then Calibre will  store the right thing in its database: `1|The Python Quants|Quants, The Python|`. However, if you try use the regular name field as a sort field -- as in your case, then Calibre will insert escape characters. 

<img width="655" alt="grafik" src="https://user-images.githubusercontent.com/1092531/88672311-9a1f8080-d0e7-11ea-8e43-83bac8cbfc4d.png">

The database entry will look like this:   `2| **Quants| The Python**|Quants, The Python|`

I added the double asterisks to clarify that the bar is inserted in the middle of the text by Calibre! And BBS then just reads the name information and displays it. So, Calibre works and BBS too.

If you really want use the sorted author name everywhere, then I would recommend to change the Calibre names back to standard, and then adapt the templates to your wishes.

The procedure for that is relatively easy:

1. You select a template from the `templates` directory, for example [author_details.html](https://github.com/rvolz/BicBucStriim/blob/master/templates/author_detail.html). As the name implies that is the details view for authors.
2. You search for `author.name` 
3. You replace `author.name` with `author.sort`

Example

```html
<div class="ui-block-a">
  <h3>{{ author.name }}</h3>
  {% if author.thumbnail %}
```

would be converted to

```html
<div class="ui-block-a">
  <h3>{{ author.sort }}</h3>
  {% if author.thumbnail %}
```

After the change, you'll get the _sorted_ name displayed, instead of the regular form.

**Comment by huber72** [comment]
Moin,

thanks for the explicit answer - that was of great help

best regards, Peter
