### ISSUE TITLE
DietPi + BicBuCStriim

### ISSUE THREAD

**Issue by Thomas-O** [rvolz/BicBucStriim#364]
Might it be possible to work with the [DietPi](https://dietpi.com/#noAction) developers to create a version of BicBucStriim for DietPi? Making BicBucStriim more accessible for those less technically adept, and also supporting users who have a SBC but may not have the money for a fancy NAS.

At present DietPi supports Ubooquity. Which is nice, but BicBucStriim would be much better. Especially in combination with a (syncthing) synchronised Calibre library.

Thanks for considering this request.

Thomas

**Comment by rvolz** [comment]
Starting with the next alpha version there is a ready-to-run Docker image planned. Since DietPi seems to support [Docker](https://dietpi.com/docs/software/programming/#docker) users should be able to run BicBucStriim by simply pulling and starting the image.

The Dockerfile and the composer dependency information used to create this image could then also be used by packagers to create packages for their distribution of choice, if Docker is no option.

Personally, I don't have the time to maintain distribution packages, there are too many distributions. But if someone wanted to create and maintain a package for DietPi, that would be the route to go forward.
